name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main  # 当推送到主分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # 使用你需要的 Python 版本

      - name: Set PYTHONPATH
        run: |
          export PYTHONPATH="$PYTHONPATH:./my_extensions"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
